import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import Key from 'App/Models/Key'

export default class extends BaseSeeder {
  public async run() {
    const uniqueKey = 'name'
    await Key.updateOrCreateMany(uniqueKey, [
      // Bloco A - Administrativo
      {
        name: 'CRA - Coord. de Registros Acadêmicos',
        is_avaible: false,
        level: 'ADMIN',
        bloco: 'A',
        piso: 'TERREO',
        numero: '001',
      },
      {
        name: 'Centro de Idiomas',
        is_avaible: false,
        level: 'ADMIN',
        bloco: 'A',
        piso: 'TERREO',
        numero: '002',
      },
      {
        name: 'Auditório',
        is_avaible: true,
        level: 'ADMIN',
        bloco: 'A',
        piso: 'TERREO',
        numero: '502',
      },
      {
        name: 'Rede de Incubadora',
        is_avaible: true,
        level: 'ADMIN',
        bloco: 'A',
        piso: 'SUPERIOR',
        numero: '003',
      },
      {
        name: 'CGAB - Chefia de Gabinete',
        is_avaible: false,
        level: 'ADMIN',
        bloco: 'A',
        piso: 'SUPERIOR',
        numero: '004',
      },
      {
        name: 'DG - Diretoria Geral',
        is_avaible: false,
        level: 'ADMIN',
        bloco: 'A',
        piso: 'SUPERIOR',
        numero: '005',
      },
      // Bloco B - Salas de Aula
      {
        name: 'Sala de Aula 06',
        is_avaible: true,
        level: 'PROFESSOR',
        bloco: 'B',
        piso: 'TERREO',
        numero: '101',
      },
      {
        name: 'Sala de Aula 07',
        is_avaible: true,
        level: 'TEA',
        bloco: 'B',
        piso: 'TERREO',
        numero: '102',
      },
      {
        name: 'Sala de Aula 08',
        is_avaible: true,
        level: 'COORDENADOR',
        bloco: 'B',
        piso: 'TERREO',
        numero: '103',
      },
      {
        name: 'Sala de Aula 09',
        is_avaible: false,
        level: 'PROFESSOR',
        bloco: 'B',
        piso: 'TERREO',
        numero: '104',
      },
      {
        name: 'Sala de Aula 10',
        is_avaible: false,
        level: 'TEA',
        bloco: 'B',
        piso: 'TERREO',
        numero: '105',
      },
      {
        name: 'Sala de Aula 11',
        is_avaible: false,
        level: 'COORDENADOR',
        bloco: 'B',
        piso: 'SUPERIOR',
        numero: '201',
      },
      {
        name: 'Sala de Aula 12',
        is_avaible: true,
        level: 'PROFESSOR',
        bloco: 'B',
        piso: 'SUPERIOR',
        numero: '202',
      },
      {
        name: 'Sala de Aula 13',
        is_avaible: true,
        level: 'TEA',
        bloco: 'B',
        piso: 'SUPERIOR',
        numero: '203',
      },
      {
        name: 'Sala de Aula 14',
        is_avaible: true,
        level: 'PROFESSOR',
        bloco: 'B',
        piso: 'SUPERIOR',
        numero: '204',
      },
      {
        name: 'Sala de Aula 15',
        is_avaible: true,
        level: 'TEA',
        bloco: 'B',
        piso: 'SUPERIOR',
        numero: '205',
      },
      // Bloco C - Salas de Aula
      {
        name: 'Sala de Aula 16',
        is_avaible: true,
        level: 'PROFESSOR',
        bloco: 'C',
        piso: 'TERREO',
        numero: '301',
      },
      {
        name: 'Sala de Aula 17',
        is_avaible: true,
        level: 'TEA',
        bloco: 'C',
        piso: 'TERREO',
        numero: '302',
      },
      {
        name: 'Sala de Aula 18',
        is_avaible: true,
        level: 'COORDENADOR',
        bloco: 'C',
        piso: 'TERREO',
        numero: '303',
      },
      {
        name: 'Sala de Aula 19',
        is_avaible: true,
        level: 'PROFESSOR',
        bloco: 'C',
        piso: 'TERREO',
        numero: '304',
      },
      {
        name: 'Sala de Aula 20',
        is_avaible: true,
        level: 'TEA',
        bloco: 'C',
        piso: 'TERREO',
        numero: '305',
      },
      {
        name: 'Sala de Aula 21',
        is_avaible: true,
        level: 'COORDENADOR',
        bloco: 'C',
        piso: 'SUPERIOR',
        numero: '401',
      },
      {
        name: 'Sala de Aula 22',
        is_avaible: true,
        level: 'PROFESSOR',
        bloco: 'C',
        piso: 'SUPERIOR',
        numero: '402',
      },
      {
        name: 'Sala de Aula 23',
        is_avaible: true,
        level: 'TEA',
        bloco: 'C',
        piso: 'SUPERIOR',
        numero: '403',
      },
      {
        name: 'Sala de Aula 24',
        is_avaible: true,
        level: 'PROFESSOR',
        bloco: 'C',
        piso: 'SUPERIOR',
        numero: '404',
      },
      {
        name: 'Sala de Aula 25',
        is_avaible: true,
        level: 'TEA',
        bloco: 'C',
        piso: 'SUPERIOR',
        numero: '405',
      },
    ])
  }
}
